on:
  push:
    paths:
      - 'steamtinkerlaunch'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'steamtinkerlaunch'

name: "ShellCheck"
permissions: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          version: v0.10.0
